/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package countdown;


import static countdown.Book.weeklyBooking;
import static countdown.CountDown.currentUser;
import static countdown.notice.d;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import java.awt.Frame;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.sql.ResultSet;


/**
 *
 * @author nishanbakunts
 */
public class SaveBookings extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form SaveBookings
     */
    
    static ArrayList<String> myBookings; 
    static ResultSet results  = null;
    
    public SaveBookings(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }
    
    
    public static void begin()
    {
        
        myBookings = new ArrayList<String>();
        
        
        
        try 
               {
                 
               // Get all the bookings by the current user for next seven days
               results =  Database.get_Statement().executeQuery("Select "
                + "Next_Login_Date, Next_Login_Time from UserTable where Username = '" + currentUser + "' AND Next_Login_Date >= CURRENT_DATE");//AND " + currentSecs + "BETWEEN Time_in_seconds AND Time_in_seconds + 5340)"); // and Last_Login_Date = '" + currentDate + "')");
              
               }
          catch (SQLException e)
                {
                    System.out.println("Error " + e);
                }        
        //System.out.println(currentDate);
          String bookedData = "";
           try 
                 
               {  
                 while (results.next())  
                  {
                 
                 
                 
                 bookedData = results.getString(1) + " " + results.getString(2);
                 myBookings.add(bookedData);
                
                  }
                
                 //System.out.println(myBookings);
              //results.close();
              
              
               }
           catch (SQLException e)
                {
                    System.out.println("Error - reading booked data " + e);
                } 
           
        
        
        
         SaveBookings savebooking = new SaveBookings(new javax.swing.JFrame(), true);
            
            savebooking.setTitle("Your bookings");
            savebooking.setAlwaysOnTop(true);
            savebooking.setLocation(d.width/4 + 80, d.height/4);
            savebooking.setVisible(true);
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        booking1 = new javax.swing.JCheckBox("", true);
        booking2 = new javax.swing.JCheckBox("", true);
        booking3 = new javax.swing.JCheckBox("", true);
        booking4 = new javax.swing.JCheckBox("", true);
        booking5 = new javax.swing.JCheckBox("", true);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("Save");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        try
        {
            if (myBookings.size() > 0)
            {
                booking1.setText(myBookings.get(0));
            }
            else
            {
                booking1.setVisible(false);
            }

        }
        catch (IndexOutOfBoundsException ie)
        {
            booking1.setSelected(false);
        }
        booking1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booking1ActionPerformed(evt);
            }
        });

        try
        {
            if (myBookings.size() > 1)
            {
                booking2.setText(myBookings.get(1));
            }

            else
            {
                booking2.setVisible(false);
                booking2.setSelected(false);
            }

            try
            {
                if (myBookings.size() > 2)
                {
                    booking3.setText(myBookings.get(2));
                }

                else
                {
                    booking3.setVisible(false);
                    booking3.setSelected(false);
                }

                try
                {
                    if (myBookings.size() > 3)
                    {
                        booking4.setText(myBookings.get(3));
                    }
                    else
                    {
                        booking4.setVisible(false);
                        booking4.setSelected(false);
                    }

                    try
                    {
                        if (myBookings.size() >= 5)
                        {
                            booking5.setText(myBookings.get(4));
                        }

                        else
                        {
                            booking5.setVisible(false);
                            booking5.setSelected(false);
                        }

                        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
                        jLabel1.setText("Below are your bookings for this week.");

                        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
                        jLabel2.setText("If you want to delete a booking, click on the checkbox to uncheck it,");

                        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
                        jLabel3.setText(" then click save to delete the booking.");

                        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                        getContentPane().setLayout(layout);
                        layout.setHorizontalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cancelButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(booking5)
                                                        .addComponent(booking4)
                                                        .addComponent(booking3)
                                                        .addComponent(booking2)
                                                        .addComponent(booking1))
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel2)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74))
                        );

                        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

                        layout.setVerticalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(booking1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(booking2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(booking3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(booking4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(booking5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cancelButton)
                                    .addComponent(okButton))
                                .addContainerGap())
                        );

                        getRootPane().setDefaultButton(okButton);
                    }

                    catch (IndexOutOfBoundsException ie)
                    {
                        booking2.setSelected(false);
                    }
                }

                catch (IndexOutOfBoundsException ie)
                {
                    booking3.setSelected(false);
                }
            }

            catch (IndexOutOfBoundsException ie)
            {
                booking4.setSelected(false);
            }
        }

        catch (IndexOutOfBoundsException ie)
        {
            booking5.setSelected(false);
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
        
        
            
        
        if (booking1.getSelectedObjects() == null)
        {
            try
        {
           results.absolute(1);
           results.deleteRow();
           Book.weeklyBooking = Book.weeklyBooking - 1;
           Book.bookings.setText(Integer.toString(weeklyBooking));
            
        }
        
        catch (SQLException se)
        {
            
        }
       
            
           
            
        }   
        else if (booking2.getSelectedObjects() == null)
        {
             try
        {
           results.absolute(2);
           results.deleteRow();
           Book.weeklyBooking = Book.weeklyBooking - 1;
           Book.bookings.setText(Integer.toString(weeklyBooking));
           
           
           
           
           
        }
            
            catch (SQLException se)
            {
                
            }
      
        }
        
         else if (booking3.getSelectedObjects() == null)
        {
             try
        {
           results.absolute(3);
           results.deleteRow();
           Book.weeklyBooking = Book.weeklyBooking - 1;
           Book.bookings.setText(Integer.toString(weeklyBooking));
        }
            
            catch (SQLException se)
            {
                
            }
        }
        
         else if (booking4.getSelectedObjects() == null)
        {
             try
        {
           results.absolute(4);
           results.deleteRow();
           Book.weeklyBooking = Book.weeklyBooking - 1;
           Book.bookings.setText(Integer.toString(weeklyBooking));
        }
            
            catch (SQLException se)
            {
                
            }
             
        }
         else if (booking5.getSelectedObjects() == null)
        {
             try
        {
           results.absolute(5);
           results.deleteRow();
           Book.weeklyBooking = Book.weeklyBooking - 1;
           Book.bookings.setText(Integer.toString(weeklyBooking));
        }
            
            catch (SQLException se)
            {
                
            }
        }
        
    }//GEN-LAST:event_okButtonActionPerformed
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void booking1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booking1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_booking1ActionPerformed
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaveBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaveBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaveBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaveBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SaveBookings dialog = new SaveBookings(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JCheckBox booking1;
    public static javax.swing.JCheckBox booking2;
    public static javax.swing.JCheckBox booking3;
    public static javax.swing.JCheckBox booking4;
    public static javax.swing.JCheckBox booking5;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;
}
